### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by aarontan-git** [cristian-frincu/navigation_waypoints_scripts#1]
Hello,

I came from your old [repo](https://github.com/cristian-frincu/simple_navigation_goals).

I am wondering, which script do I run and how do I run it? (I am new to ROS).

Do I simply edit file.csv for points that I'd like my robot to traverse to? (What are the titles of each of the 4 columns?) - or do I edit waypointNodes.csv?

I have cloned it in to my catkin_ws/src already and did catkin_make.

Thank you,
Aaron

**Comment by cristian-frincu** [comment]
Hey Arron,
You should not manually edit any csv files. 
You are supposed to run the .python files as instructed in the README. 

The python files will create the .csv fro you.
