### ISSUE TITLE
Transformation

### ISSUE THREAD

**Issue by mpena2099** [cristian-frincu/navigation_waypoints_scripts#3]
First of all, greate work, @cristian-frincu!

Question: could you explain the two lines above from nodeSelection_1.py? 
```
x_transform = (x)*(0.02) - 10
y_transform = (y)*(-0.02) + 10
```

I know that you are transforming the coordinates of the image into something possible to be received by the ROS, but I did not understand the calculation.

Thanks!
Mauricio

**Comment by cristian-frincu** [comment]
Hi,
The input coordinates (x,y) are in the map coordinate and resolution frame. I am transforming them into the coordinates of the robot. 

The resolution of my map is 0.02 meters per pixel, 
And It is offset by 10m. 

Where (0,0) is in the robot coordinate frame, it is (-10,10) in the the map coordinate frame.

I hope this helps

**Comment by mpena2099** [comment]
Yes, it helps. Thanks!
